# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tion.proto\x12\x05poker\"^\n\x06\x41\x63tion\x12 \n\x04type\x18\x01 \x02(\x0e\x32\x12.poker.Action.Type\x12\x0b\n\x03\x62\x65t\x18\x02 \x01(\x05\"%\n\x04Type\x12\x08\n\x04\x46OLD\x10\x00\x12\x08\n\x04\x43\x41LL\x10\x01\x12\t\n\x05RAISE\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=23
  _ACTION._serialized_end=117
  _ACTION_TYPE._serialized_start=80
  _ACTION_TYPE._serialized_end=117
# @@protoc_insertion_point(module_scope)
